In [4]:
from pprint import pprint
from numpy import array, zeros, diag, diagflat, dot, linalg


def jacobi(A,b,N=25,x=None):
    """Solves the equation Ax=b via the Jacobi iterative method."""
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = zeros(len(A[0]))

    # Create a vector of the diagonal elements of A                                                                                                                                                
    # and subtract them from A                                                                                                                                                                     
    D = diag(A)
    R = A - diagflat(D)

    # Iterate for N times                                                                                                                                                                          
    for i in range(N):
        x = (b - dot(R,x)) / D
    return x

A = array([[1.0,0.3824],[0.7128,2.0]])
b = array([2.0,4.4835])
guess = array([0.0,0.0])

sol = jacobi(A,b,N=1,x=guess)
sol2= jacobi(A,b,N=2,x=guess)
sol3 = sol2-sol
print ("A:")
pprint(A)

print ("b:")
pprint(b)

print ("x:")
pprint(sol)
pprint(sol2)
pprint(sol3)

norma = linalg.norm(sol3)
pprint(norma)

A:
array([[1.    , 0.3824],
       [0.7128, 2.    ]])
b:
array([2.    , 4.4835])
x:
array([2.     , 2.24175])
array([1.1427548, 1.52895  ])
array([-0.8572452, -0.7128   ])
1.1148780977860495


In [ ]:
from pprint import pprint
from numpy import array, zeros, diag, diagflat, dot

def jacobi(A,b,N=25,x=None):
    """Solves the equation Ax=b via the Jacobi iterative method."""
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = zeros(len(A[0]))

    # Create a vector of the diagonal elements of A                                                                                                                                                
    # and subtract them from A                                                                                                                                                                     
    D = diag(A)
    R = A - diagflat(D)

    # Iterate for N times                                                                                                                                                                          
    for i in range(N):
        x = (b - dot(R,x)) / D
    return x

A = array([[4,4],[]])
b = array([2.2,-1.3,4.5])
guess = array([1.0,2.0,3.0])

sol = jacobi(A,b,N=5,x=guess)

print ("A:")
pprint(A)

print ("b:")
pprint(b)

print ("x:")
pprint(sol)