In [1]:
import numpy as np

In [3]:
## definir quantas funções você quer pro polinomio


def g0(x):
    return 1

def g1(x):
    return x

def g2(x):
    return x**2

def g3(x):
    return x**3

dicionarioFuncoes = { 0:g0, 1:g1, 2:g2, 3:g3}

In [5]:
## transcrever aqui as tabelas de valores de x e y dados no exercicio

arr_x = [-1.5708,-1.1781,-0.7854,-0.3927,0,0.3927,0.7854,1.1781,1.5708]

arr_y = [-1,-0.9239,-0.7071,-0.3827,0,0.3827,0.7071,0.9239,1]

In [10]:


def fillmg(dicionarioFuncoes, arr_x):
    matrizGtrans = []
    for i in range(4):
        f = dicionarioFuncoes[i]
        tmpArr = []
        for x in arr_x:
            tmpArr.append(f(x))
        matrizGtrans.append(tmpArr)
    matrizGtransnp = np.array(matrizGtrans)
    return matrizGtransnp


matrizG = fillmg(dicionarioFuncoes,arr_x)

In [22]:
print(matrizG.transpose())

[[ 1.         -1.5708      2.46741264 -3.87581177]
 [ 1.         -1.1781      1.38791961 -1.63510809]
 [ 1.         -0.7854      0.61685316 -0.48447647]
 [ 1.         -0.3927      0.15421329 -0.06055956]
 [ 1.          0.          0.          0.        ]
 [ 1.          0.3927      0.15421329  0.06055956]
 [ 1.          0.7854      0.61685316  0.48447647]
 [ 1.          1.1781      1.38791961  1.63510809]
 [ 1.          1.5708      2.46741264  3.87581177]]


In [23]:
x, residuals, rank, s= np.linalg.lstsq(matrizG.transpose(),arr_y)

<ipython-input-23-ce17fc54e010>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, residuals, rank, s= np.linalg.lstsq(matrizG.transpose(),arr_y)


In [25]:
print(x)
print(residuals)

[ 0.00000000e+00  9.85512111e-01 -2.22044605e-16 -1.41883864e-01]
[0.00010306]
